/*-------------------------------------------------------------------------*
 * DCK.H:                                                                  *
 * Included in all files except DCK.C.                                     *
 *-------------------------------------------------------------------------*/

#include <std.h>
#include "gui\gui.hpp"
#include "gui\dialog.hpp"
#include "gui\menu.hpp"
#include "zlib.h"
#include "defs.h"
#include "externs.h"
#include "object.hpp"
#include "proto.h"
#include "strdefs.h"
#include "window.h"
#include "typcnvt.hpp"
#pragma hdrstop
