SO_LINETABLE    so_table[] =
{
    { "Floor",      SOP_ADJTYPE,    SOP_INTEGER,    SC_FLOOR },
    { "FloorTex",   SOP_STRING,     SOP_NONE,       SC_FLOORTEX },
    { "Light",      SOP_ADJTYPE,    SOP_INTEGER,    SC_LIGHT },
    { "BLineType",  SOP_INTEGER,    SOP_NONE,       SC_BLTYPE },
    { "ObjInsert",  SOP_INTEGER,    SOP_NONE,       SC_OBJINSERT },
    { "Ceil",       SOP_ADJTYPE,    SOP_INTEGER,    SC_CEIL },
    { "CeilTex",    SOP_STRING,     SOP_NONE,       SC_CEILTEX },
    { "SecType",    SOP_INTEGER,    SOP_NONE,       SC_SECTYPE },
    { "BLineLTex",  SOP_STRING,     SOP_NONE,       SC_BLLTEX },
    { "BLineUTex",  SOP_STRING,     SOP_NONE,       SC_BLUTEX },
    { "BLineFTex",  SOP_STRING,     SOP_NONE,       SC_BLFTEX },
    { "SecFindTag", SOP_NONE,       SOP_NONE,       SC_SECTAG },
    { "BLineSetTag",SOP_NONE,       SOP_NONE,       SC_BLSETTAG },
    { NULL,         0,              0,              0 }
};

