.AUTODEPEND

#		*Translator Definitions*
CC = bcc32 -WX -v -N
TASM = TASM /zi
TLIB = tlib
TLINK = tlink32
LIBPATH = C:\CODE\LIB;C:\BC45\LIB
INCLUDEPATH = C:\CODE\INCLUDE;C:\BC45\INCLUDE


#		*Implicit Rules*
.c.obj:
  $(CC) -c {$< }

.cpp.obj:
  $(CC) -c {$< }

.asm.obj:
  $(TASM) {$< }

#		*List Macros*

EXE_dependencies =  \
test.obj \
guid.lib

#		*Explicit Rules*
test.exe: $(EXE_dependencies)
 $(TLINK) /ax/v/m/s/S:FF00/P-/L$(LIBPATH) @&&|
c0x32.obj+
test.obj
test,test
guid.lib+
zlib_bf.lib+
bgi32.lib+
dpmi32.lib+
cw32.lib
|


