#define uchar unsigned char
#define unint unsigned short
#define ushort unsigned short
#define ulong unsigned long
#ifndef bool
#define bool uchar
#endif

#include <dir.h>
#include <string.h>
#include <conio.h>
#include <ctype.h>
#include <stdio.h>
#include <bios.h>
#include <dos.h>
#include <stdarg.h>
#include <stdlib.h>
#include <alloc.h>
#include <attrdefs.h>
#include <io.h>
#include <fcntl.h>
#include <sys\stat.h>
#include <process.h>

#define TRUE    1
#define FALSE   0
#define ON      1
#define OFF     0
